#include<iostream.h>
#include<conio.h>
int main()
{
clrscr();
int a,b,mul;
cout<<"\t"<<"\t"<<"\t"<<"Multiplication";
cout<<"Enter your first Number = ";
cin>>a;
cout<<"Enter your second number = ";
cin>>b;
mul=a*b;
cout<<" The mulitiplied number is = ";
cout<<mul;
return 0;
}
// You can add many number values to do that you have to do a change. i.e, give more values in 6th line (Eg: int a,b,c,d,e,.....,mul;)//
